apiVersion: extensions/v1beta1

kind: Deployment

metadata:

  name: crypto

spec:

  replicas: 1

  template:

    metadata:

      labels:

        app: crypto

    spec:

      containers:

       - name: crypto

         image: gebareg.azurecr.io/crypto

         ports:

          - containerPort: 80